version: '3.9'

services:
  firewall:
    build: ./firewall
    volumes:
      - ./firewall:/app
    ports:
      - "${FIREWALL_PORT}:${FIREWALL_PORT}"
    networks:
      - net
    depends_on:
      - reverse-proxy

  reverse-proxy:
    build: ./reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net
    depends_on:
      - server1
      - server2

  server1:
    build: ./backend-servers/server1
    volumes:
      - ./backend-servers/server1:/app
    expose:
      - "5000"
    networks:
      - net

  server2:
    build: ./backend-servers/server2
    volumes:
      - ./backend-servers/server2:/app
    expose:
      - "5000"
    networks:
      - net

  honeypot:
    build: ./honeypot
    volumes:
      - ./honeypot:/app
    networks:
      - net
    depends_on:
      - firewall

  file-receiver:
    build: ./file-receiver
    volumes:
      - ./file-receiver:/app
      - ./file-receiver/uploads:/app/uploads
    networks:
      - net
    depends_on:
      - firewall

  client:
    build: ./client
    volumes:
      - ./client:/app
    networks:
      - net
    depends_on:
      - firewall

  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard:/app
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
    networks:
      - net
    depends_on:
      - firewall

networks:
  net:
    driver: bridge
